### ISSUE TITLE
Agree on investment, DFC and salaries

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#49] opened 2022-07-06 12:06 UTC
**Description:**

Agree on investment ( self funding) will be treated and what tokens they get
how DCF works - cumulative or static at beginning
and on salary levels

**Definition of done:**

- [ ] Agreement made

**Comment by Mrak1985** [comment] 2022-07-07 11:16
Duplicate of another issue #61

**Closed as completed by Mrak1985** 2022-07-07 11:17 UTC
Labels: duplicate, finance
