### ISSUE TITLE
Hire legal rep for Tonomy

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#89] opened 2022-07-18 08:29 UTC
Description

We should ask 2 students to join and work for Tonomy or Legal firm which can work for free in exchange for technology. Good comment to be made that ID with SSI will have  been widely adopted in the EU by 2025 so it will make them think about their future development

**Definition of done:**

- [x] Students are reached and agreed or not for interview
- [x] Interview for Legal students if they agreed upon that
- [x] Contact 3 Legal companies and make a proposal for them (or may be to send cold email to 20 of them)
- [x] final decision is made about legal rep for Tonomy and offered is sent

**Comment by Mrak1985** [comment] 2022-07-20 09:57
Duplicate of 45

**Comment by Mrak1985** [comment] 2022-08-04 17:42
Robert's interview was performed, we agree to hire him  https://www.notion.so/tonomy-foundation/320602f5422949a2b814465a5e9354c2?v=6d5b01f1cf4f443cbd519a61c6a20fe6&p=7dfa6d0b26c642a1894a7419ea76bb8b&pm=s

**Comment by Mrak1985** [comment] 2022-08-10 13:41
@kamitor Should contact on more 1 student and 3 legal companies as well

**Comment by kamitor** [comment] 2022-08-11 06:59
okay 2 more

**Comment by Mrak1985** [comment] 2022-08-11 08:01
@kamitor either one student or legal company. Can both actually.

**Comment by kamitor** [comment] 2022-08-24 13:38
26'th i will have a talk with the counsillor

**Comment by kamitor** [comment] 2022-08-24 13:38
26'th i will have a talk with the counsillor

**Comment by kamitor** [comment] 2022-08-26 10:12
Currently student is writing document

**Closed as completed** 2022-08-29 15:41 UTC
Labels: human resources

**Comment by kamitor** [comment] 2022-08-30 10:13
https://www.linkedin.com/in/hildevanderbaan/ contacted

**Comment by kamitor** [comment] 2022-08-30 10:13
https://www.linkedin.com/in/hildevanderbaan/ contacted
